### PR TITLE
Include miles abbreviations

### PR DESCRIPTION
**Pull request by MrChrisW**
Fixing [#1006](https://github.com/duckduckgo/zeroclickinfo-goodies/issues/1006)

Let me know if I've missed something :wink: 

CC// @elohmrow @mintsoft

### CODE REVIEW

**Comment by elohmrow** [comment]
closed in https://github.com/elohmrow/Convert-Pluggable/commit/2500223abd2bb7f95a8a3e7e0550225c961d38d9

**Comment by MrChrisW** [comment]
@elohmrow Just out of interest, is there any reason this wasn't merged? Would have happily rebased after Mintsofts PR was merged. :smile: Thanks

**Comment by elohmrow** [comment]
@MrChrisW - i merged it in, but by hand - your code should be there ... it's early here and i saw two pull requests and after doing @mintsoft, there was a conflict.  so i just hand edited the code - cuz it's early :)

**Comment by MrChrisW** [comment]
@elohmrow Got it! Whatever is easiest :smile:!

Take it you'll also need to update versions and release? I'm just not sure how that works, always interested to learn :laughing:

**Comment by elohmrow** [comment]
@MrChrisW - usually all i do is update it here and then copy it local and then update on cpan.  so your changes should be in C::P-0.027 on cpan as soon as PAUSE actually grabs and indexes :)

**Comment by MrChrisW** [comment]
@elohmrow Ahh right! I'm interested in knowing what's involved with managing a Perl module so thanks for the brief explanation.

**Comment by elohmrow** [comment]
@MrChrisW - don't follow my work flow then :)

**Comment by MrChrisW** [comment]
@elohmrow hahaha "do as I say and not as I do" :+1:

**Pull request closed without merging**
