### PR TITLE
Add cups as a 'volume' unit

### PR DESCRIPTION
**Pull request by kbhat95**
This is in reference to the issue raised over [here](https://github.com/duckduckgo/zeroclickinfo-goodies/issues/1188), in order to add "ml to cups" conversion support in DuckDuckGo.

### CODE REVIEW

**Comment by elohmrow** [comment]
thanks @kbhat95, but i don't think this is being used any more.  i think ddg are headed in a different direction - but i will note @moollaza just in case i am wrong.

**Comment by kbhat95** [comment]
@elohmrow, oh, really? This was what I was asked to do when I asked how to proceed on IRC, albeit not by @moollaza. Let's wait for the final word then. :)

**Comment by moollaza** [comment]
@elohmrow we're still using your awesome Convert-Pluggable for now, but eventually, yes I'd like to make our conversions more modular and in our own repo so it's a little easier to contribute.

I'll be sure to let you know when we're no longer using this.

**Comment by elohmrow** [comment]
ok - i will merge this in later today, as i am busy now.

thanks for letting me know!

**Comment by elohmrow** [comment]
@kbhat95 i have merged this pr and released a new version of C::P which contains it to CPAN

**Comment by elohmrow** [comment]
@moollaza i have previously offered to give someone on your end maint of the module if it is helpful ... also, i wanted to re-write it using something like Moo{se} if that is useful ... further, I am entirely happy to provide an api for a new version that you could use to update the module, add units, etc.  up to you!

**Comment by kbhat95** [comment]
@elohmrow thanks!

**Comment by moollaza** [comment]
@elohmrow thanks a lot! I'll get back to you on the maintenance and API :+1:

**Comment by elohmrow** [comment]
@moollaza - i have today made a first pass at this locally.  i've cleaned up subs and args/returns, re-written it in Moo::Lax, and moved the object returned by get_units() to a db (+ORM).  i like the last bit because it, among other things, allows for an interface (API) for CRUD-ing units.  i don't like it because it slows it down a bit.  two questions:
    1.  what db engine do you prefer? (obviously orm makes it loosely-coupled, but doesn't hurt to use the right one right away)
    2.  any other ideas to improve it $right_now?

thanks!

**Pull request merged**
